/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Compute: typeof import('./../src/components/Compute.vue')['default']
    DynamicSeparator: typeof import('./../src/components/DynamicSeparator.vue')['default']
    DynamicSeparatorV2: typeof import('./../src/components/DynamicSeparator-v2.vue')['default']
    DynamicSeparotor: typeof import('./../src/components/DynamicSeparotor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    Modals: typeof import('./../src/components/Modals.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreList: typeof import('./../src/views/puzzle/components/ScoreList.vue')['default']
    StxIconCar: typeof import('~icons/icon/car')['default']
    TestModal: typeof import('./../src/components/TestModal.vue')['default']
    Tile: typeof import('./../src/views/puzzle/components/Tile.vue')['default']
  }
}
